# Generated by Django 4.2 on 2023-12-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('sub_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='subtile')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripison')),
            ],
            options={
                'verbose_name': ('post',),
                'verbose_name_plural': 'posty',
            },
        ),
    ]
